CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BINARY(16) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (USER_ID),
    INDEX idx_user_email (EMAIL),
    INDEX idx_user_username (USERNAME)
);

CREATE TABLE IF NOT EXISTS PROFILES (
    PROFILE_ID BINARY(16) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    PROFILE_IMAGE_URL VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    ADDRESS VARCHAR(255),
    DESCRIPTION TEXT,
    IS_DELETED BOOLEAN NOT NULL,
    VIEW_COUNT INT NOT NULL,
    USER_ID BINARY(16) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (PROFILE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_profile_title (TITLE),
    INDEX idx_profile_phone_number (PHONE_NUMBER),
    INDEX idx_profile_created_at (CREATED_AT)
);

CREATE TABLE IF NOT EXISTS PROFILES_VIEWS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PROFILE_ID BINARY(16) NOT NULL,
    VIEWED_AT DATETIME(6) NOT NULL,
    VIEWER_IP VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES(PROFILE_ID) ON DELETE CASCADE,
    INDEX idx_profile_viewed_at (VIEWED_AT),
    INDEX idx_profile_viewer_ip (VIEWER_IP)
);